Impl dispatch
scapella/trimal pull request #96
Opened 2024-01-27 10:41 UTC by althonos

Hi @nicodr97 !

Sorry for the small delay in getting this implemented, I finally got to sit down and work on some extra code besides what I need for my PhD :smile: 

I added the `cpu_features` from Google as a `git` submodule, and updated the CMake files to compile it as a subdirectory. `cpu_features` is available under the Apache 2.0 license so there is no licensing issue here. When a new `Manager` is creeate, it checks the local CPU feature flags to check what backend is supported, using a mixture of compilation flags and runtime flags:

- on `x86`, it checks for SSE2 and AVX2
- on `x86-64`, SSE2 is always available, it checks for AVX2
- on `arm`, it checks for NEON
- on `aarch64`, NEON is always supported. 

It's still possible to disable AVX2, NEON, or SSE2 at compile time; but now a single binary can be compiled and distributed for all platforms.

2024-02-02 12:13 UTC, nicodr97 requested changes
Very nice!

Given that the `platform` value depends on the specific compilation parameter passed by the user, is the necessary to check it all around? That is, doesn't `platform == ComputePlatform::SSE2` means that `HAVE_SSE2` is defined?

Thank you for your contribution!

2024-02-02 12:13 UTC, nicodr97 commented on source/Statistics/Manager.cpp
> +        platform = ComputePlatform::NEON;
```
        if (features.neon != 0) {
            platform = ComputePlatform::NEON;
        }
```

2024-02-03 10:11 UTC, althonos commented
> Given that the platform value depends on the specific compilation parameter passed by the user, is the necessary to check it all around? That is, doesn't platform == ComputePlatform::SSE2 means that HAVE_SSE2 is defined?

Yes, `platform == ComputePlatform::SSE2` means `HAVE_SSE2` is defined; however you cannot remove the include guards because the SSE2 statistics (e.g. `SSE2Similarity`) may not be defined if `HAVE_SSE2` is not defined. If you remove the include guards, you'll get compile errors because some classes are not defined.

You could include stub files to still compile a mostly empty `SSE2Similarity` in have `HAVE_SSE2` is not defined, but that's definitely more work than just add a few include guards at the right locations for basically the same result.

2024-02-05 09:08 UTC, nicodr97 approved these changes

2024-02-05 09:10 UTC, merged